<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rp_Dimpenghasilan_ayah</name>
   <tag></tag>
   <elementGuidId>35efd220-521d-4234-984b-a4b81181fb64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dim-penghasilan_ayah']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dim-penghasilan_ayah</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8c0dc77e-5464-4fef-8d2b-ac94194bb96d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b59a3e3d-f70c-4dc1-82b4-f82bd9f9d875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dim-penghasilan_ayah</value>
      <webElementGuid>52b2e4e4-8f70-475c-9e41-9499c33df25e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>eb93640d-190b-499d-8a53-c37a1b57914b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Dim[penghasilan_ayah]</value>
      <webElementGuid>caa6d8a6-b3ab-4b4c-b2a3-18b1c2849a32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Penghasilan Ayah</value>
      <webElementGuid>5233edef-8d65-4ba3-8f32-358d4081c993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dim-penghasilan_ayah&quot;)</value>
      <webElementGuid>1cc33a9f-b5df-4144-8077-4771342adcd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dim-penghasilan_ayah']</value>
      <webElementGuid>f72f03fe-225e-4706-ad7a-dab3083a350c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab_4']/div[16]/div/div/input</value>
      <webElementGuid>a0880496-c90a-4c82-97ff-be631de1dc58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[16]/div/div/input</value>
      <webElementGuid>02db5004-ee82-4a6a-8b6f-5bb9197dfba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'dim-penghasilan_ayah' and @name = 'Dim[penghasilan_ayah]' and @placeholder = 'Penghasilan Ayah']</value>
      <webElementGuid>e0f551e6-ba7e-479d-8bac-77394ce01cc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
