<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kelurahan  Desa_Dimkelurahan</name>
   <tag></tag>
   <elementGuidId>cad9e1da-d461-4537-a519-c4740a3c01b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dim-kelurahan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dim-kelurahan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b97b095a-6e4f-4fb6-928a-d82b370159a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>765ecdc3-3cd8-49bf-921a-84a8d69d184c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dim-kelurahan</value>
      <webElementGuid>f9f8c16f-2fe8-4b61-9261-03a2cfb4c852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>280cb456-7035-4ea0-ad51-f3b14cd777fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Dim[kelurahan]</value>
      <webElementGuid>fe4e130f-18b8-42c7-898e-57f869943f2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Kelurahan</value>
      <webElementGuid>2bf782ee-ff59-4977-a735-7c071d18f8d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dim-kelurahan&quot;)</value>
      <webElementGuid>d4f17f6e-21b1-4427-9045-f7cef8590d1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dim-kelurahan']</value>
      <webElementGuid>da015415-effb-4228-b143-ddebf8341a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='grid-system1-body']/div[12]/div/input</value>
      <webElementGuid>9790e144-4d30-48b4-91eb-b2b2971fccec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/input</value>
      <webElementGuid>ec4bc29a-09e6-4cc4-8d1b-5b25e9a67b7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'dim-kelurahan' and @name = 'Dim[kelurahan]' and @placeholder = 'Kelurahan']</value>
      <webElementGuid>ba0c36ed-8b83-4104-9d42-5bcb73a761bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
