<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rp_Dimpenghasilan_ibu</name>
   <tag></tag>
   <elementGuidId>4bba2d8a-3f73-40f1-9506-e71914cb4853</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dim-penghasilan_ibu']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dim-penghasilan_ibu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c7b45941-88ff-4b11-98ad-6a73c125881c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8f68a5c5-c8ce-4671-9619-ff093d437d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dim-penghasilan_ibu</value>
      <webElementGuid>f7e98bef-be90-473f-977c-24ab258cf373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ea4c5cb7-bf4b-4639-ad03-d50ae5c9679d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Dim[penghasilan_ibu]</value>
      <webElementGuid>05052bb1-0dd5-46a7-a8a3-192596f6d821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Penghasilan Ibu</value>
      <webElementGuid>c1cf3d0b-a5ed-4481-ba99-6ba9eeff024b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dim-penghasilan_ibu&quot;)</value>
      <webElementGuid>4675bd2d-bc42-4ba8-bceb-7bee63a99e51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dim-penghasilan_ibu']</value>
      <webElementGuid>a480ef23-be15-4792-9730-dcee97cd4812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab_4']/div[21]/div/div/input</value>
      <webElementGuid>70d6b0c1-d7ca-48a9-9741-517d27f6126d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[21]/div/div/input</value>
      <webElementGuid>4b82a349-effb-4206-882d-50770926c84b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'dim-penghasilan_ibu' and @name = 'Dim[penghasilan_ibu]' and @placeholder = 'Penghasilan Ibu']</value>
      <webElementGuid>4aace8f5-94e0-4f58-b3e9-55978749cfbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
